version: "3.7"

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: binotify_web
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./src/api:/var/www/html/api
    environment:
      - DOCKER_ENV=1
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: binotify_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
